name: Nick Ager's blog
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
paginate: 5
gems: [jekyll-paginate, jekyll-sitemap]
exclude: [vendor] # for travis - Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Ager's blog
email: nick.ager@gmail
description: > # this means to ignore newlines until "baseurl:"
  Nick Ager, software developer; iOS, Swift, Objective-C, C++, C, Javascript, Haskell, Ruby, Smalltalk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nickager.com" # the base hostname & protocol for your site
twitter_username: nickager
github_username:  nickager
github:
    user: nickager
    project: nickager.github.io
